[window]
option_as_alt = "Both"
decorations = "None"

[font]
normal = { family = "UDEV Gothic 35HS", style = "Regular" }

# https://github.com/toml-lang/toml/issues/657
[[keyboard.bindings]]
key = "Slash"
mods = "Control"
chars = "\u001f"
