[[plugins]]
repo = 'dense-analysis/ale'
if = 0
hook_add = '''
  " 各種 filetype の設定は myruntime/ftplugin 配下に

  let g:ale_fixers = {
      \ '*': ['remove_trailing_lines', 'trim_whitespace']
      \ }

  let g:ale_fix_on_save = 1

  nnoremap <Leader>8 :<C-u>ALEFix<CR>
'''
