[[plugins]]
repo = 'junegunn/vim-easy-align'
on_map = { xn = '<Plug>(LiveEasyAlign)' }
hook_add = '''
xmap ga <Plug>(LiveEasyAlign)
nmap ga <Plug>(LiveEasyAlign)
'''

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = [
  'markdown',
  'html',
  'rust',
  'javascript',
  'jsx',
  'javascriptreact',
  'typescript',
  'tsx',
  'typescriptreact',
  'vue',
  'svelte',
]
on_path = '\.mdx\?$'
# for preact
# let g:user_emmet_settings = emmet#merge(get(g:, 'user_emmet_settings'), { 'jsx': { 'attribute_name': {'class': 'class'}}})
hook_add = '''
let g:user_emmet_leader_key = "\<C-f>"
'''

[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'
on_map = ['gS', 'gJ']
# gS : split
# gJ : join

# 重いときに j/k を叩きまくった後の硬直を緩和してくれる
[[plugins]]
repo = 'rhysd/accelerated-jk'
on_map = {n = '<Plug>(accelerated_jk'}
hook_add = '''
nmap j <Plug>(accelerated_jk_gj)
nmap k <Plug>(accelerated_jk_gk)
nmap gj <Plug>(accelerated_jk_j)
nmap gk <Plug>(accelerated_jk_k)
'''

[[plugins]]
repo = 'LumaKernel/vim-goimports'
on_ft = 'go'
hook_add = '''
let g:goimports_simplify = 1
let g:goimports_loclist = 0
'''

# Python Import Improvement
[[plugins]]
repo = 'relastle/vim-nayvy'
on_ft = "python"
hook_add = '''
let g:nayvy_import_path_format = 'all_absolute'
'''

[[plugins]]
repo = 'kamykn/spelunker.vim'
on_event = 'CursorHold'
hook_add = '''
let &spellfile = expand('$HOME/dotfiles/vim/spellfile.utf-8.add')
let g:spelunker_spell_bad_group = 'Warning'
let g:spelunker_complex_or_compound_word_group = 'Warning'
let g:enable_spelunker_vim = 1

let g:spelunker_disable_auto_group = 1

function! SpelunkerInit(...) abort
  if line('$') < 2000
    call spelunker#check()
  endif
endfunction

augroup spelunker
  autocmd!
  autocmd BufWinEnter,BufWritePost ++nested * call SpelunkerInit()
  autocmd BufWinEnter,BufWritePost ++nested * call timer_start(1000 * 2, function('SpelunkerInit'))
augroup END
'''

[[plugins]]
repo = 'osyo-manga/vim-jplus'
on_map = {n = '<Plug>'}
hook_add = '''
nmap J <Plug>(jplus)
'''

[[plugins]]
repo = 'lambdalisue/reword.vim'
on_map = ':'
