# Open Browser
[[plugins]]
repo = 'tyru/open-browser.vim'
on_map = "<Plug>(openbrowser"
hook_add = '''
nmap gx <Plug>(openbrowser-smart-search)
vmap gx <Plug>(openbrowser-smart-search)
'''

[[plugins]]
repo = 'itchyny/vim-gitbranch'
if = "has('patch-8.2.0001') || has('nvim')"
on_source = 'lightline.vim'

# Status Line
[[plugins]]
repo = 'itchyny/lightline.vim'
on_event = 'BufRead'
depends = ['vim-gitbranch']
if = "has('patch-8.2.0001') || has('nvim')"
hook_add = '''
let g:lightline = {
  \   'colorscheme': 'seoul256',
  \   'active': {
  \     'left':  [
  \       [ 'mode', 'paste' ],
  \       [ 'gitbranch', 'filename', 'filestat', 'modified', 'readonly' ],
  \       [ 'charvaluehex' ],
  \     ],
  \     'right': [
  \       [ 'lineinfo' ],
  \       [ 'fileformat', 'fileencoding', 'filetype' ],
  \     ],
  \   },
  \   'inactive': {
  \     'left':  [
  \       [ 'gitbranch', 'filename', 'filestat', 'modified', 'readonly' ],
  \     ],
  \     'right': [
  \       [ 'lineinfo' ],
  \       [ 'fileformat', 'fileencoding', 'filetype' ],
  \     ],
  \   },
  \   'component': {
  \     'charvaluehex': '0x%B',
  \   },
  \   'component_function': {
  \     'mode': 'MyMode',
  \     'gitbranch': 'MyGitBrnach',
  \     'readonly': 'MyReadonly',
  \     'filename': 'MyFilename',
  \     'filestat': 'MyFilestat',
  \     'modified': 'MyModified',
  \     'fileformat': 'MyFileformat',
  \   },
  \ }

function! MyGitBrnach()
  if &buftype is# 'help'
    return ''
  elseif !empty(getcmdwintype())
    return ''
  elseif &filetype is# 'fern'
    return ''
  endif
  let res = gitbranch#name()
  if empty(res)
    return 'no git'
  endif
  return printf('git:%s', res)
endfunction

function! MyReadonly()
  if &buftype is# 'help'
    return ''
  elseif !empty(getcmdwintype())
    return ''
  elseif &filetype is# 'fern'
    return ''
  endif
  return &ro is# 1 ? 'RO' : ''
endfunction

function! MyFilename()
  let path = vital#vital#import("Path")
  if &buftype is# 'help'
    return ''
  elseif &filetype is# 'fern'
    return ''
  endif
  let full = expand('%:p')
  let rel = path.relative(full, getcwd())
  if rel[0] ==# '.'
    return full
  endif
  return rel
endfunction

" if executable('stat')
if has('unix')
  let g:MyStatCache = {}
  function! MyFilestat()
    let filename = g:MyGetFilename()

    if empty(filename)
      return filename
    endif

    if has_key(g:MyStatCache, filename)
      return g:MyStatCache[filename]
    endif

    let res = ''
    silent! let res = trim(
      \   system(printf("stat --format '%%a' %s", shellescape(filename)))
      \ )
    if match(res, '^\d\d\d$') == -1
      return ''
    endif
    let g:MyStatCache[filename] = res
    return res
  endfunction

  function! MyStatCacheDeleteThis()
    let filename = g:MyGetFilename()

    if empty(filename)
      return filename
    endif

    silent! unlet! g:MyStatCache[filename]
  endfunction

  function! MyGetFilename()
    if &buftype is# 'help'
      return ''
    elseif !empty(getcmdwintype())
      return ''
    elseif &filetype is# 'fern'
      let filename = GetFernDirname()
    else
      let filename = expand('%:p')
    endif

    return filename
  endfunction

  augroup MyStatCache
    autocmd BufEnter ++nested * call g:MyStatCacheDeleteThis()
  augroup END
else
  function! MyFilestat()
    return ''
  endfunction
endif

function! MyMode()
  if &buftype is# 'help'
    return ''
  elseif !empty(getcmdwintype())
    return ''
  elseif &filetype is# 'fern'
    return GetFernDirname()
  endif
  return toupper(mode())
endfunction

function! MyFileformat()
  if &buftype is# 'help'
    return ''
  elseif !empty(getcmdwintype())
    return ''
  elseif &filetype is# 'fern'
    return GetFernDirname()
  endif

  if &ff is# 'dos'
    return '\r\n'
  elseif &ff is# 'unix'
    return '\n'
  elseif &ff is# 'mac'
    return '\r'
  endif
  return ''
endfunction

function! MyModified()
  if &buftype is# 'help'
    return ''
  elseif !empty(getcmdwintype())
    return ''
  elseif &filetype is# 'fern'
    return ''
  endif

  return &modified is# 1 ? '*' : ''
endfunction

function! GetFernDirname()
  let path = get(matchlist(expand('%'), 'fern://[^/]\+/file://\(.*\)\$'), 1, '')
  return path
endfunction
'''

[[plugins]]
repo = 'itchyny/vim-cursorword'
on_event = 'CursorHold'
if = '!g:from_pwsh && !has("nvim")'

[[plugins]]
repo = 'RRethy/vim-illuminate'
on_event = 'BufRead'
if = 'has("nvim")'

# Fern Plugins
[[plugins]]
repo = 'yuki-yano/fern-preview.vim'
on_ft = 'fern'
depends = 'fern.vim'
hook_add = '''
function! s:init_fern_preview() abort
  nmap <silent> <buffer> p     <Plug>(fern-action-preview:toggle)
  nmap <silent> <buffer> <C-j> <Plug>(fern-action-preview:auto:toggle)
  nmap <silent> <buffer> <C-n> <Plug>(fern-action-preview:scroll:down:half)
  nmap <silent> <buffer> <C-p> <Plug>(fern-action-preview:scroll:up:half)
endfunction
augroup my-fern-preview
  autocmd! *
  autocmd FileType ++nested fern call s:init_fern_preview()
augroup END
'''

# [[plugins]]
# repo = 'lambdalisue/fern-git-status.vim'
# depends = 'fern.vim'
# hook_add = '''
#   let g:fern_git_status#disable_untracked = 1
# '''
#
# [[plugins]]
# repo = 'lambdalisue/fern-mapping-git.vim'
# depends = 'fern.vim'

[[plugins]]
repo = 'lambdalisue/fern-bookmark.vim'
on_path = '^fern://'
depends = 'fern.vim'

# Window Manager
[[plugins]]
repo = 't9md/vim-choosewin'
on_cmd = [
  'ChooseWin',
  'ChooseWinSwap',
]
hook_add = '''
nnoremap <Leader>cw :<C-u>ChooseWin<CR>
nnoremap <Leader>cs :<C-u>ChooseWinSwap<CR>
'''

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
on_cmd = [
  'Files',
  'GFiles',
  'History',
  'Buffers',
  'Colors',
  'Commands',
]
hook_add = '''
" if has('win32')
"   " Windows: preview は相性があまりよくない
"   "   UTF-8 と CP932 を両方見れるようにするのがまず難しいそう
"   let $FZF_DEFAULT_OPTS = '--tabstop=4'
" else
"   let file_viewer = 'cat {} 2>/dev/null'
"   let dir_viewer = 'ls {}'
"   if executable('bat')
"     let file_viewer = 'bat --pager=never --color=always --style=numbers {} 2>/dev/null'
"   endif
"   if executable('exa')
"     let dir_viewer = 'exa --tree --color always {}'
"   endif
"   let $FZF_DEFAULT_OPTS = printf('--tabstop=4 --preview-window hidden:up --preview "%s || %s"', file_viewer, dir_viewer)
" endif
" 
" if executable('ag') && $FZF_DEFAULT_COMMAND ==# ''
"   let $FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'
" endif

if has('nvim')
  let g:fzf_layout = { 'window': 'call my#CreateCenteredFloatingWindow()' }
endif

command! -bang Colors call fzf#vim#colors({'options': '--preview ""'}, <bang>0)


function! RipgrepFzf(query, fullscreen) abort
  let command_fmt = 'rg --hidden --column --line-number --no-heading --color=always --smart-case -- %s || true'
  let initial_command = printf(command_fmt, shellescape(a:query))
  let reload_command = printf(command_fmt, '{q}')
  let spec = {'options': [
    \   '--preview-window', 'hidden:up:noborder',
    \   '--phony',
    \   '--query', a:query,
    \   '--bind', 'change:reload:'.reload_command
    \ ]}
  call fzf#vim#grep(initial_command, 1, fzf#vim#with_preview(spec), a:fullscreen)
endfunction

command! -nargs=* -bang Rg call RipgrepFzf(<q-args>, <bang>0)


nnoremap <silent> ,f  :<C-u>Files<CR>
nnoremap <silent> ,df :<C-u>GFiles<CR>
nnoremap <silent> ,dd :<C-u>GFiles?<CR>
nnoremap <silent><expr> ,cf ':<C-u>Files<CR>' .. expand('<cfile>')
nnoremap <silent><expr> ,cdf ':<C-u>GFiles<CR>' .. expand('<cword>')
nnoremap <silent><expr> ,cdd ':<C-u>GFiles?<CR>' .. expand('<cword>')
nnoremap <silent> <Leader>i :<C-u>History<CR>
nnoremap <silent> <Leader>ls :<C-u>Buffers<CR>
nnoremap <silent> <Leader>col :<C-u>Colors<CR>

function! s:RgPrompt() abort
  call inputsave()
  let str = input("Rg > ")
  call inputrestore()
  if !empty(str)
    execute printf('Rg %s', str)
  endif
endfunction

function! s:RgLiterallyPrompt() abort
  call inputsave()
  let str = input("Rg Literally > ")
  call inputrestore()
  if !empty(str)
    call s:RgLiterally(str)
  endif
endfunction

function! s:RgLiterally(str) abort
  let literal = a:str

  let regex = Regex7Escape(literal)
  let regex = substitute(regex, '[\n\r]', '[\s\S]?', 'g')
  let regex = substitute(regex, '\t', '\\t', 'g')

  execute printf('Rg %s', regex)
endfunction

function! s:RgLiterallySelected() abort
  let yank_save = @@
  normal! gvy
  let copied = @@
  let @@ = yank_save

  call s:RgLiterally(copied)
endfunction

nnoremap <expr><silent> ,cg ':call <SID>RgLiterally(expand("<cword>"))<CR>'
nnoremap ,g :<C-u>call <SID>RgPrompt()<CR>
nnoremap ,rg :<C-u>call <SID>RgLiterallyPrompt()<CR>
xnoremap ,g :<C-u>call <SID>RgLiterallySelected()<CR>
xnoremap ,cg :<C-u>call <SID>RgLiterllySelected()<CR>
'''

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_map = { xn = '<Plug>(LiveEasyAlign)' }
hook_add = '''
xmap ga <Plug>(LiveEasyAlign)
nmap ga <Plug>(LiveEasyAlign)
'''

[[plugins]]
repo = 'HiPhish/info.vim'
on_cmd = 'Info'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = [
  'markdown',
  'html',
  'rust',
  'javascript',
  'jsx',
  'javascriptreact',
  'typescript',
  'tsx',
  'typescriptreact',
  'vue',
  'svelte',
]
on_path = '\.mdx\?$'
# for preact
# let g:user_emmet_settings = emmet#merge(get(g:, 'user_emmet_settings'), { 'jsx': { 'attribute_name': {'class': 'class'}}})
hook_add = '''
let g:user_emmet_leader_key = "\<C-f>"
'''

[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'
on_map = ['gS', 'gJ']
# gS : split
# gJ : join

# 重いときに j/k を叩きまくった後の硬直を緩和してくれる
[[plugins]]
repo = 'rhysd/accelerated-jk'
on_map = {n = '<Plug>(accelerated_jk'}
hook_add = '''
nmap j <Plug>(accelerated_jk_gj)
nmap k <Plug>(accelerated_jk_gk)
nmap gj <Plug>(accelerated_jk_j)
nmap gk <Plug>(accelerated_jk_k)
'''

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'
if = '!has("nvim")'
on_ft = [
  "javascript",
  "jsx",
  "javascriptreact",
  "typescript",
  "typescriptreact",
  "tsx",
]

[[plugins]]
repo = 'othree/yajs.vim'
if = '!has("nvim")'
on_ft = [
  "javascript",
  "typescript",
  "javascriptreact",
  "typescriptreact"
]

[[plugins]]
repo = 'rhysd/committia.vim'
on_ft = 'gitcommit'
on_path = 'COMMIT_EDITMSG$'
hook_add = '''
let g:committia_hooks = {}
function! g:committia_hooks.edit_open(info)
  if a:info.vcs ==# 'git' && getline(1) ==# ''
    startinsert
  endif
  " nmap <buffer><C-n> <Plug>(committia-scroll-diff-down-half)
  " nmap <buffer><C-p> <Plug>(committia-scroll-diff-up-half)
endfunction
'''

[[plugins]]
repo = 'LumaKernel/fern-mapping-fzf.vim'
on_ft = 'fern'
depends = ['fzf', 'fern.vim']
hook_add = '''
function! Fern_mapping_fzf_customize_option(spec)
  let a:spec.options .= ' --multi'
  return fzf#vim#with_preview(a:spec)
endfunction

function! Fern_mapping_fzf_before_all(dict)
  if !len(a:dict.lines)
    return
  endif
  return a:dict.fern_helper.async.update_marks([])
endfunction

function! s:reveal(dict)
  execute "FernReveal -wait" a:dict.relative_path
  if len(a:dict.lines) > 2
    execute "normal \<Plug>(fern-action-mark:set)"
  endif
endfunction

let g:Fern_mapping_fzf_file_sink = function('s:reveal')
let g:Fern_mapping_fzf_dir_sink = function('s:reveal')
'''

[[plugins]]
repo = 'LumaKernel/fern-mapping-reload-all.vim'
depends = ['fern.vim']
on_ft = 'fern'
hook_add = '''
function! s:init_fern_mapping_reload_all() abort
  nmap <buffer> R <Plug>(fern-action-reload:all)
endfunction
augroup my-fern-mapping-reload-all
  autocmd! *
  autocmd FileType ++nested fern call s:init_fern_mapping_reload_all()
augroup END
'''

[[plugins]]
repo = 'LumaKernel/vim-zenspace'
on_event = 'CursorHold'

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html', 'htmldjango']

[[plugins]]
repo = 'LumaKernel/vim-jsx-pretty'
on_ft = [
  'javascript',
  'javascriptreact',
  'jsx',
  'typescript',
  'typescriptreact',
  'tsx',
]

[[plugins]]
repo = 'vim-python/python-syntax'
on_ft = 'python'
hook_add = '''
let g:python_highlight_all = 1
'''

[[plugins]]
repo = 'LumaKernel/vim-goimports'
on_ft = 'go'
hook_add = '''
let g:goimports_simplify = 1
let g:goimports_loclist = 0
'''

# Colorizer
[[plugins]]
if = "has('nvim')"
on_event = 'CursorHold'
repo = 'norcalli/nvim-colorizer.lua'
hook_post_source = '''
lua require'colorizer'.setup()
'''

# Lang: C++
[[plugins]]
repo = 'Mizuchi/STL-Syntax'
on_ft = ['c', 'cpp']
[[plugins]]
repo = 'rhysd/wandbox-vim'
on_ft = ['c', 'cpp']

# Lang: OCaml
[[plugins]]
repo = 'ocaml/vim-ocaml'
on_ft = 'ocaml'
[[plugins]]
repo = 'let-def/ocp-indent-vim'
on_ft = 'ocaml'

# Lang: Fish
[[plugins]]
repo = 'dag/vim-fish'
on_ft = 'fish'

# Lang: Django
[[plugins]]
repo = 'tweekmonster/django-plus.vim'
on_ft = 'djangohtml'

# Lang: TOML
[[plugins]]
repo = 'cespare/vim-toml'
on_path = '\.toml$'

# Lang: JSON
[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'
hook_add = '''
let g:vim_json_syntax_conceal = 0
'''
[[plugins]]
repo = 'neoclide/jsonc.vim'
on_ft = 'json'

# Lang: PowerShell
[[plugins]]
repo = 'PProvost/vim-ps1'
on_ft = 'ps1'

# Lang: Q#
[[plugins]]
repo = 'gootorov/q-sharp.vim'
on_path = '\.qs$'

# Lang: Coq
[[plugins]]
repo = 'LumaKernel/coqpit.vim'
on_ft = 'coq'
hook_source = '''
let g:coqpit_auto_move=1
let g:coqpit_one_window=0

function! MyCoqMaps()
  nnoremap <silent> <C-C> :CoqLaunch<CR>
  nnoremap <silent> <Leader>j :CoqNext<CR>
  nnoremap <silent> <Leader>k :CoqBack<CR>
  nnoremap <silent> <Leader>l :CoqToCursor<CR>
  nnoremap <silent> <Leader>g :CoqToLast<CR>
  nnoremap <silent> <Leader>t :MoveToTop<CR>

  nnoremap <Leader>compute :CoqQuery Compute .<Left>
  nnoremap <Leader>print :CoqQuery Print .<Left>
  nnoremap <Leader>check :CoqQuery Check .<Left>
  nnoremap <Leader>search :CoqQuery Search ().<Left><Left>
endfunction

augroup my-coq
  au!
  au FileType ++nested coq :call MyCoqMaps()
augroup END

if has('win32')
  let g:coqpit_coq_executable = 'C:\Coq8.10\bin\coqidetop.exe'
elseif has('unix')
  let g:coqpit_coq_executable = expand('~/.local/bin/coq/V8.11.1/bin/coqidetop')
endif

function! CoqSwitchStyle() abort
  if !exists('b:coquilleIDE') || b:coquilleIDE.dead()
    return
  endif

  let b:coquilleIDE.my_style = !get(b:coquilleIDE, 'my_style', 0)
  if b:coquilleIDE.my_style
    let b:coquilleIDE.style_checked = 'last_line'
    let b:coquilleIDE.style_queued  = 'last_line'
  else
    let b:coquilleIDE.style_checked = 'all'
    let b:coquilleIDE.style_queued  = 'all'
  endif
  CoqRecolor
endfunction

command! CoqSwitchStyle call CoqSwitchStyle()
'''

# Lang: Svelte
[[plugins]]
repo = 'evanleck/vim-svelte'
on_ft = 'svelte'
on_path = '\.svelte$'
rev = 'main'

# Lang: Markdown
[[plugins]]
repo = 'rhysd/vim-gfm-syntax'
on_ft = 'markdown'

# Lang: Prisma
[[plugins]]
repo = 'pantharshit00/vim-prisma'
on_path = '\.prisma$'

# --------------

[[plugins]]
repo = 'LumaKernel/nvim-visual-eof.lua'
on_event = 'CursorHold'
if = "has('nvim')"
hook_post_source ='''
lua require'visual-eof'.setup { hl_EOL = 'NonText'; no_autocmd = true }
lua require'my_visual_eof'()
'''

[[plugins]]
# :StripWhitespace
repo = 'ntpeters/vim-better-whitespace'
on_event = 'CursorHold'
hook_add = '''
let g:better_whitespace_enabled = 1
let g:strip_whitespace_on_save = 0
let g:strip_max_file_size = 5000
command! -bar TrimWhitespace StripWhitespace
command! -bar WhitespaceStrip StripWhitespace
command! -bar WhitespaceTrim StripWhitespace
'''

# Python Import Improvement
[[plugins]]
repo = 'relastle/vim-nayvy'
on_ft = "python"
hook_add = '''
let g:nayvy_import_path_format = 'all_absolute'
'''

[[plugins]]
repo = 'Xuyuanp/scrollbar.nvim'
on_event = 'CursorHold'
hook_add = '''
augroup my_config_scrollbar_nvim
  autocmd!
  let s:sc_show = "silent! lua require('scrollbar').show()"
  let s:sc_clear = "silent! lua require('scrollbar').clear()"
  exe "autocmd BufEnter    * ++nested" s:sc_show
  exe "autocmd BufLeave    * ++nested" s:sc_clear

  exe "autocmd CursorMoved * ++nested" s:sc_show
  exe "autocmd VimResized  * ++nested" s:sc_show

  exe "autocmd FocusGained * ++nested" s:sc_show
  exe "autocmd FocusLost * ++nested" s:sc_clear
augroup end

let g:scrollbar_shape = {
  \ 'head': '+',
  \ 'body': '|',
  \ 'tail': '+',
  \ }

function! ClearScrollBar() abort
silent! lua require('scrollbar').clear()
endfunction

command! ClearScrollBar call ClearScrollBar()

nnoremap <silent> <SPACE><SPACE> :<C-u>ClearScrollBar<CR>
'''

[[plugins]]
repo = 'jparise/vim-graphql.git'
on_ft = 'graphql'
if = '!has("nvim")'

[[plugins]]
repo = 'kamykn/spelunker.vim'
on_event = 'CursorHold'
hook_add = '''
let &spellfile = expand('$HOME/dotfiles/vim/spellfile.utf-8.add')
let g:spelunker_spell_bad_group = 'Warning'
let g:spelunker_complex_or_compound_word_group = 'Warning'
let g:enable_spelunker_vim = 1

let g:spelunker_disable_auto_group = 1

function! SpelunkerInit(...) abort
  if line('$') < 2000
    call spelunker#check()
  endif
endfunction

augroup spelunker
  autocmd!
  autocmd BufWinEnter,BufWritePost ++nested * call SpelunkerInit()
  autocmd BufWinEnter,BufWritePost ++nested * call timer_start(1000 * 2, function('SpelunkerInit'))
augroup END
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
if = 'has("nvim")'
on_event = 'BufRead'
depends = 'impatient.nvim'
hook_post_update = 'TSUpdate'
hook_post_source = '''
lua <<EOF
  require'nvim-treesitter.configs'.setup {
    ensure_installed = "maintained",
    indent = {
      enable = true,
    },
    highlight = {
      enable = true,
    },
  }
  local parser_config = require "nvim-treesitter.parsers".get_parser_configs()
  -- parser_config.prisma = {
  --   install_info = {
  --     url = "~/workspace/tree-sitter-prisma",
  --     files = {"src/parser.c"},
  --   },
  --   filetype = "prisma",
  -- }
EOF
'''

[[plugins]]
repo = 'luma-dev/dps-godoc'
depends = ["denops.vim"]
on_cmd = 'Godoc'
on_path = '^godoc://'
on_source = 'denops.vim'

[[plugins]]
repo = 'LumaKernel/as-it-is.vim'
on_cmd = [
  'Waii',
  'Uaii',
  'Aaii',
]

[[plugins]]
repo = 'subnut/nvim-ghost.nvim'
if = 'has("nvim")'
merged = 0
on_cmd = 'GhostTextEnable'
hook_add = '''
let g:nvim_ghost_disabled = 1
'''
hook_post_source = '''
function! s:setup_ghost(amatch) abort
  if get(g:, 'nvim_ghost_disabled', 0)
    return
  endif
  if &buftype !=# 'nofile'
    return
  endif
  if &ft !=# ''
    return
  endif
  exe 'file' matchlist(a:amatch, '[^/\\]*$')[0]
endfunction
augroup nvim_ghost_user_autocommands
  au!
  au User www.reddit.com,www.stackoverflow.com ++nested set filetype=markdown
  au User www.reddit.com,www.github.com ++nested set filetype=markdown
  au User *github.com ++nested set filetype=markdown
  au User *.com,*.net,*.io,*.jp,*.org ++nested call <SID>setup_ghost(expand("<amatch>"))
augroup END
'''

[[plugins]]
repo = 'osyo-manga/vim-jplus'
on_map = {n = '<Plug>'}
hook_add = '''
nmap J <Plug>(jplus)
'''

[[plugins]]
repo = 'lambdalisue/reword.vim'
on_map = ':'

[[plugins]]
repo = 'lambdalisue/suda.vim'
on_event = 'BufRead'
hook_add = '''
let g:suda_smart_edit = v:true
'''

[[plugins]]
repo = 'liuchengxu/vista.vim'
on_cmd = 'Vista'
hook_add = '''
nnoremap <silent> <Space>ac :<c-u>Vista coc<cr>
'''

[[plugins]]
repo = 'simeji/winresizer'
on_map = "<space>w"
hook_add = '''
let g:winresizer_start_key = '<space>w'
'''
