[[plugins]]
repo = 'mhinz/vim-startify'
hook_add = '''
  function s:repeat(str, num)
    return join(map(range(a:num), 'a:str'), '')
  endfunction

  " g:mapping_descriptions でマッピングの説明を管理
  " let g:mapping_descriptions = ['マッピング名', '説明']
  " で自由に追加できる

  function! g:MappingDescriptions()
    let s:S = vital#vital#import('Data.String')
    let left_width = max(map(deepcopy(g:mapping_descriptions), 'strlen(v:val[0])')) + 4
    let width = max(map(deepcopy(g:mapping_descriptions), 'l:left_width + strlen(v:val[1])'))
    let strs = map(deepcopy(g:mapping_descriptions), '"|  " .. s:S.pad_right(s:S.pad_right(v:val[0], l:left_width) .. v:val[1], l:width) .. "  |"')

    return [
          \   '+' .. s:repeat('-', 2 + width + 2) .. '+',
          \ ] + strs + [
          \   '+' .. s:repeat('-', 2 + width + 2) .. '+',
          \ ]
  endfunction

  let g:my_startify_message = [
        \   "\uf120  Welcome to \ue7c5 !",
        \   "",
        \   "Sessions.vim をプロジェクトフォルダ内に置くことでセッションを保存",
        \   "もしくは :SSave を使う",
        \   "",
        \ ]

  let g:startify_enable_special = 0
  let g:startify_session_dir = '~/.tmp/vim/startify-session'

  let g:startify_custom_header = 'startify#pad(g:my_startify_message + g:MappingDescriptions())'

  " .git とか (VCS) が見つかるまで上に登って change directory する
  let g:startify_change_to_dir = 1
  let g:startify_change_to_vcs_root = 1


  " 最新の状態にする
  let g:startify_update_oldfiles = 0

  let g:startify_session_persistence = 1

  let g:startify_bookmarks = [
        \   '~/cp',
        \   '~/mynote',
        \   '~/work',
        \   '~/dotfiles',
        \   '~/vim-make-plugin',
        \   '~/.cache/dein/repos',
        \]

  function! s:MyColorSelections()
    let names = [
          \   'onedark',
          \   'tender',
          \   'spring-night',
          \   'iceberg',
          \   'darkblue',
          \   'red_alert',
          \ ]
    return map(copy(names), { i, colo -> { 'line': colo, 'cmd': printf('SwitchColorScheme %s', colo) } })
  endfunction

  function! s:MyRefs()
    return [
          \   { 'line': 'GNU Make' , 'cmd': 'call LynxCache("https://www.gnu.org/software/make/manual/make.html")' },
          \ ]
  endfunction

  function! g:LynxCache(url) abort
    let URI = vital#vital#import('Web.URI')
    let HTTP = vital#vital#import('Web.HTTP')
    let filename = expand('~/docs') .. '/' .. URI.encode(a:url)
    try
      if !filereadable(filename)
        call HTTP.request({'url': a:url, 'method': 'GET', 'outputFile': filename})
      endif
    catch /.*/
      echom '[LynxCache] Something wrong. Couldn''t make cache.'
      exe 'Ref lynx' a:url
      return
    endtry
    exe 'Ref lynx' filename
  endfunction

  function! s:MyLinks()
    let l:res = [
          \   { 'line': 'カラースキーム一覧' , 'url': 'http://colorswat.ch/vim/list?p=2&o=star' },
          \   { 'line': 'カラースキーム一覧' , 'url': 'http://vimcolors.com/' },
          \   { 'line': 'Nerd Fonts チートシート' , 'url': 'https://www.nerdfonts.com/cheat-sheet' },
          \ ]

    for el in l:res
      if has_key(el, 'url')
        let el.line ..= ' : ' .. el.url
        let el.cmd = ':OpenBrowser ' .. el.url
        unlet el.url
      endif
    endfor

    return l:res
  endfunction


  let g:startify_commands = [
        \   ':DeinClean',
        \   ':call dein#recache_runtimepath()',
        \   ':call dein#build()',
        \   ':call dein#remote_plugins()',
        \   ':CocConfig',
        \   ':History',
        \   ':Colors',
        \ ]

  let g:startify_lists = [
        \ { 'type': 'bookmarks', 'header': ["   \uf461 ブックマーク"] },
        \ { 'type': 'files',     'header': ["   \uf490 最近開いたファイル"] },
        \ { 'type': 'dir',       'header': ["   \uf490 最近開いたファイル in " .. getcwd()] },
        \ { 'type': 'sessions',  'header': ["   \ue706 セッション"] },
        \ { 'type': 'commands',  'header': ["   \uf489 コマンド"] },
        \ { 'type': function('s:MyColorSelections'),  'header': ["   \u26a1 カラーテーマ"] },
        \ { 'type': function('s:MyRefs'),  'header': ["   \uf002 リファレンス"] },
        \ { 'type': function('s:MyLinks'),  'header': ["   \u26a1 便利リンク"] },
        \ ]

  nnoremap <silent> ,s :<C-u>Startify \| only<CR>
'''


hook_post_source = '''
  augroup init_vim
    au User StartifyReady silent! nunmap <buffer> q
    au User StartifyReady silent! nunmap <buffer> q
    au User StartifyReady silent! nunmap <buffer> t
    au User StartifyReady silent! nunmap <buffer> T
    au User StartifyReady silent! nunmap <buffer> T
  augroup END
'''
