version: "3.8"

services:
  entrance:
    network_mode: host
    build:
      context: .
      dockerfile: ./docker/entrance/Dockerfile
  caddy:
    network_mode: host
    build:
      context: .
      dockerfile: ./docker/caddy/Dockerfile
