tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "universal-ctags/universal-ctags"
brew "fish"
brew "gawk"
brew "go"
brew "gpg"
brew "coreutils"
brew "ripgrep"
brew "ghq"
brew "pyenv"
brew "tmux"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
