---
version: 2
root-markers:
  - RCS/
  - SCCS/
  - CVS/
  - .git/
  - .svn/
  - .hg/
  - .bzr/
  - _darcs/
  - .git
# command define
commands:
  - title: Reload
    command: :reload-config

  - title: Editor
    os: windows
    command: notepad
    arguments:
      - "${FILENAME}"
  - title: Editor
    os: linux
    command: gedit
    # Linux no method generic GUI editor open
    arguments:
      - ${FILENAME}
  - title: Editor
    os: darwin
    command: open
    arguments:
      - '-e'
      - ${FILENAME}

  - title: Filer
    os: windows
    command: cmd
    arguments:
      - '/c'
      - 'explorer /select,${FILENAME}'
  - title: Filer
    os: darwin
    # Linux   no method generic filer open
    command: open
    arguments:
      - '-R'
      - ${FILENAME}

  - title: Browser
    os: darwin
    # Windows no method generic browser open
    # Linux   no method generic browser open
    command: open
    arguments:
      - '-a'
      - 'Safari'
      - ${FILENAME}

  - title: Open
    os: windows
    command: rundll32
    arguments:
      - "url.dll,FileProtocolHandler"
      - "${FILENAME}"
  - title: Open
    os: linux
    command: xdg-open
    arguments:
      - ${FILENAME}
  - title: Open
    os: darwin
    command: open
    arguments:
      - ${FILENAME}

# linter,formatter setting
tools:
  cppcheck-lint: &cppcheck-lint
    lint-command: 'cppcheck --enable=style --error-exitcode=1 ${INPUT}'
    lint-stdin: false
    lint-formats:
      - '%f:%l:%c: %m'
    root-markers:
    - compile_commands.json

  vale-lint: &vale-lint
    lint-command: 'vale --relative --output line ${INPUT}'
    lint-stdin: false
    lint-ignore-exit-code: true
    lint-formats:
      - '%f:%l:%c:%*[^:]:%m'

  vint-lint: &vint-lint
    lint-command: 'vint --enable-neovim --style-problem --stdin-display-name ${INPUT} -'
    lint-stdin: true

  nvcheck-lint: &nvcheck-lint
    lint-command: 'nvcheck ${INPUT}'
    lint-stdin: false
    lint-formats:
      - '%f:%l: %m'
    root-markers:
    - dict.yml

  nvcheck-format: &nvcheck-format
    format-command: 'nvcheck -r ${INPUT}'
    format-stdin: false
    root-markers:
    - dict.yml

  markdownlint-lint: &markdownlint-lint
    lint-command: 'npx --no-install markdownlint --stdin'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%m'

  markdownlint-format: &markdownlint-format
    format-command: 'npx --no-install markdownlint --fix ${INPUT}'
    format-stdin: false

  pandoc-markdown-format: &pandoc-markdown-format
    format-command: 'pandoc -f markdown -t gfm -sp --tab-stop=2'
    format-stdin: true

  pandoc-rst-format: &pandoc-rst-format
    format-command: 'pandoc -f rst -t rst -s --columns=79'
    format-stdin: true

  jsonlint-lint: &jsonlint-lint
    lint-command: 'jsonlint -c'
    lint-stdin: true
    lint-formats:
      - 'line %l, col %c, found: %m'

  # not work
  # jq-lint: &jq-lint
  #   lint-command: 'jq'
  #   lint-stdin: true
  #   lint-offset: 1
  #   lint-formats:
  #     - '%m at line %l, column %c'

  jq-format: &jq-format
    format-command: 'jq .'
    format-stdin: true

  fixjson-format: &fixjson-format
    format-command: 'fixjson'
    format-stdin: true

  shellcheck-lint: &shellcheck-lint
    lint-command: 'shellcheck -s bash -f gcc -x -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  shfmt-format: &shfmt-format
    format-command: 'shfmt -ln bash -i 2 -bn -ci -sr -kp'
    format-stdin: true

  flake8-lint: &flake8-lint
    lint-command: 'flake8 --stdin-display-name ${INPUT} -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'
    root-markers:
      - setup.cfg
      - tox.ini
      - .flake8

  mypy-lint: &mypy-lint
    lint-command: 'mypy --show-column-numbers'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'
    root-markers:
      - setup.cfg
      - mypy.ini

  rubocop-lint: &rubocop-lint
    lint-command: 'bundle exec rubocop --format emacs --force-exclusion --stdin ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'
    root-markers:
    - Gemfile
    - Rakefile
    - .rubocop.yml

  rubocop-format: &rubocop-format
    format-command: 'bundle exec rubocop --auto-correct-all --stdin ${INPUT} | sed -e "1,/^=/d"'
    format-stdin: true
    root-markers:
    - Gemfile
    - Rakefile
    - .rubocop.yml

  rufo-format: &rufo-format
    format-command: 'bundle exec rufo ${INPUT}'
    format-stdin: false
    root-markers:
    - Gemfile
    - Rakefile
    - .rufo

  yamllint-lint: &yamllint-lint
    lint-command: 'yamllint --strict --format parsable ${INPUT}'
    lint-stdin: false
    lint-formats:
      - '%f:%l:%c: [%trror] %m'
      - '%f:%l:%c: [%tarning] %m'
    env:
      - 'PYTHONIOENCODING=UTF-8'

  restructuredtext-lint-lint: &restructuredtext-lint-lint
    lint-command: 'restructuredtext-lint --encoding utf-8 --level warning --format text ${INPUT}'
    lint-stdin: false
    lint-ignore-exit-code: true
    lint-formats:
      - '%tARNING %f:%l %m'
      - '%tRROR %f:%l %m'

  textlint-lint: &textlint-lint
    lint-command: 'npx --no-install textlint -f unix --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m [%trror/%r]'
    root-markers:
      - .textlintrc

  eslint-lint: &eslint-lint
    lint-command: 'npx --no-install -- eslint_d --fix-dry-run -f unix --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    root-markers:
      - .git

  eslint-format: &eslint-format
    format-command: 'npx --no-install -- eslint_d --fix ${INPUT}'
    format-stdin: false
    root-markers:
      - package.json
      - .eslintrc.js
      - .eslintrc.yaml
      - .eslintrc.yml
      - .eslintrc.json

  stylelint-lint: &stylelint-lint
    lint-command: 'npx --no-install stylelint --formatter unix --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: false
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m [%trror]'
      - '%f:%l:%c: %m [%tarning]'
    root-markers:
      - .stylelintrc.json

  htmllint-lint: &htmllint-lint
    lint-command: 'npx --no-install htmllint ${INPUT}'
    lint-stdin: false
    lint-formats:
      - '%f: line %l, col %c, %m'
    root-markers:
      - .htmllintrc

  prettier-format: &prettier-format
    format-command: 'npx --no-install prettier ${INPUT}'
    format-stdin: false

  excitetranslate-hover: &excitetranslate-hover
    hover-command: 'excitetranslate'
    hover-stdin: true

# languages setting
languages:
  vim:
    - <<: *vint-lint

  markdown:
    # - <<: *markdownlint-lint
    # - <<: *textlint-lint
    # - <<: *vale-lint
    # - <<: *nvcheck-lint
    # - <<: *nvcheck-format
    # - <<: *prettier-format
    # - <<: *pandoc-markdown-format

  json:
    - <<: *jsonlint-lint
    - <<: *jq-format
    - <<: *fixjson-format
    - <<: *prettier-format

  json5:
    - <<: *fixjson-format
    - <<: *prettier-format

  text:
    - <<: *textlint-lint
    - <<: *vale-lint
    - <<: *nvcheck-lint
    - <<: *nvcheck-format

  help:
    - <<: *textlint-lint
    - <<: *vale-lint
    - <<: *nvcheck-lint
    - <<: *nvcheck-format

  cpp:
    - <<: *cppcheck-lint

  c:
    - <<: *cppcheck-lint

  sh:
    - <<: *shellcheck-lint
    - <<: *shfmt-format

  yaml:
    - <<: *yamllint-lint
    - <<: *prettier-format

  rst:
    - <<: *restructuredtext-lint-lint
    - <<: *textlint-lint
    - <<: *vale-lint
    - <<: *nvcheck-lint
    - <<: *nvcheck-format
    - <<: *pandoc-rst-format

  javascript:
    - <<: *eslint-lint
    - <<: *eslint-format

  typescript:
    - <<: *eslint-lint
    # - <<: *eslint-format
    # - <<: *prettier-format

  typescriptreact:
    - <<: *eslint-lint
    # - <<: *eslint-format
    # - <<: *prettier-format

  css:
    - <<: *stylelint-lint
    - <<: *prettier-format

  scss:
    - <<: *stylelint-lint
    - <<: *prettier-format

  sass:
    - <<: *stylelint-lint

  less:
    - <<: *stylelint-lint

  sugarss:
    - <<: *stylelint-lint

  python:
    - <<: *flake8-lint
    - <<: *mypy-lint

  ruby:
    - <<: *rubocop-lint
    - <<: *rubocop-format
    - <<: *rufo-format

  graphql:
    - <<: *prettier-format

  vue:
    - <<: *prettier-format

  html:
    - <<: *htmllint-lint
    - <<: *prettier-format

  _:
    - <<: *excitetranslate-hover
...
