[template-editorconfig]
prefix = ["temp-editorconfig", "editorconfig-temp", "ec-temp", "temp-ec"]
body = """
root = true

[*]
end_of_line = lf
insert_final_newline = true
indent_style = space
indent_size = 2
charset = utf-8

[*.md]
trim_trailing_whitespace = false

[{Makefile,*.make}]
tindent_style = tab
"""

[template-npmrc]
prefix = ["temp-npmrc", "npmrc-temp", "engine-strict-true", "strict-engine"]
body = """
engine-strict=true
"""
