[schema-prettier]
prefix = "schema-prettier"
body = '''
"$schema": "http://json.schemastore.org/prettierrc",
'''

[schema-tsconfig]
prefix = "schema-tsconfig"
body = '''
"$schema": "http://json.schemastore.org/tsconfig",
'''

[bun-tsconfig]
prefix = "bun-tsconfig"
body = '''
{
  "compilerOptions": {
    "lib": ["ESNext"],
    "target": "ESNext",
    "module": "ESNext",
    "moduleDetection": "force",
    "jsx": "react-jsx",
    "allowJs": true,

    /* Bundler mode */
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "verbatimModuleSyntax": true,
    "noEmit": true,

    /* Linting */
    "skipLibCheck": true,
    "strict": true,
    "noFallthroughCasesInSwitch": true,
    "forceConsistentCasingInFileNames": true
  }
}
'''
