name: GitHub Actions CI

on:
  push:
      branches:
      - master


jobs:
  windows:
    runs-on: windows-latest
    env:
      exit-not-admin: 1
    timeout-minutes: 30
    steps:
      - name: echo path
        run: echo ${env:PATH}

      - name: which vim
        run: which vim

      - name: script
        run: |
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/LumaKernel/dotfiles/master/install-win.ps1')

      - name: scoop version
        run:
          scoop --version

      - name: which vim
        run: which vim

      - name: which gvim
        run: which gvim

      - name: test vim
        run:
          vim --cmd "try | so ~/.vimrc | catch /.*/ | qa! | endtry | qa!" -u NONE

