name: GitHub Actions CI

on:
  push:
      branches:
      - master


jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: script
        run: |
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/LumaKernel/dotfiles/master/install-win.ps1')

