[[plugins]]
repo = "LumaKernel/coqpit.vim"
on_ft = "coq"
hook_source = '''
  let g:coqpit_auto_move=1
  let g:coqpit_one_window=0

  function! MyCoqMaps()
    nnoremap <silent> <C-C> :CoqLaunch<CR>
    nnoremap <silent> <Leader>j :CoqNext<CR>
    nnoremap <silent> <Leader>k :CoqBack<CR>
    nnoremap <silent> <Leader>l :CoqToCursor<CR>
    nnoremap <silent> <Leader>g :CoqToLast<CR>
    nnoremap <silent> <Leader>t :MoveToTop<CR>

    nnoremap <Leader>compute :CoqQuery Compute .<Left>
    nnoremap <Leader>print :CoqQuery Print .<Left>
    nnoremap <Leader>check :CoqQuery Check .<Left>
    nnoremap <Leader>search :CoqQuery Search ().<Left><Left>
  endfunction

  augroup my-coq
    au!
    au FileType coq :call MyCoqMaps()
  augroup END

  if has('win32')
    let g:coqpit_coq_executable = 'C:\Coq8.10\bin\coqidetop.exe'
  elseif has('unix')
    let g:coqpit_coq_executable = expand('~/.local/bin/coq/V8.11.1/bin/coqidetop')
  endif

'''
