hook_add = '''
"
  " -- ALE
  " let g:ale_linters['cpp'] = ['gcc']
  " let g:ale_linters['cmake'] = ['cmakelint']
  " let g:ale_fixers['cpp'] = [
  "      \   'clang-format',
  "      \ ]
  " let g:ale_fixers['cmake'] = [
  "      \   'cmakeformat'
  "      \ ]
  " let g:ale_cpp_gcc_options = '-std=c++14 -Wall -Wextra -Wpedantic -DDEBUG -DDEBUG_OUT=std::cout'



  " -- QuickRun
  " 'type' : 'cpp/g++' とすることで明示的に 'cpp/g++' の設定を継承する

  " -w : Inhibit all warning messages. : すべての警告を禁止する

  let g:quickrun_config = get(g:, 'quickrun_config', {})
  let g:quickrun_config['cpp'] = {
  \ 'type' : 'cpp/g++',
  \ 'command' : 'g++',
  \ 'cmdopt' : '-DDEBUG -DDEBUG_OUT=std::cout -w -std=c++17',
  \ }
  let g:quickrun_config['cpp-no-debug'] = {
  \ 'type' : 'cpp/g++',
  \ 'command' : 'g++',
  \ 'cmdopt' : '-DNDEBUG -w -std=c++17',
  \ }

  autocmd init_vim FileType cpp nnoremap <buffer><expr> <Leader>l ':ccl\|QuickRun -type "cpp-no-debug"' . "\<CR>"


'''

[[plugins]]
repo = 'Mizuchi/STL-Syntax'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'rhysd/wandbox-vim'
