hook_add = '''
  " ALE
  " let g:ale_linters['javascript'] = ['eslint']
  " let g:ale_fixers['javascript'] = [
  "      \   'eslint',
  "      \ ]
  " let g:ale_javascript_prettier_use_local_config = 1
'''

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'heavenshell/vim-jsdoc'
hook_add = '''
  let g:jsdoc_enable_es6 = 1
  au FileType javascript nnoremap <buffer> <Leader>d :JsDoc
'''
