hook_add = '''
  " ALE
  " let g:ale_linters['python'] = [
  "      \   'flake8',
  "      \   'mypy',
  "      \ ]
  "
  " let g:ale_fixers['python'] = [
  "      \   'add_blank_lines_for_python_control_statements',
  "      \   'autopep8',
  "      \ ]
  "
  "
  " let g:python3_host_prog = "python"
  " let g:ale_python_flake8_executable = g:python3_host_prog
  " let g:ale_python_flake8_options = '-m flake8'
  " let g:ale_python_autopep8_executable = g:python3_host_prog
  " let g:ale_python_autopep8_options = '-m autopep8'
  " let g:ale_python_isort_executable = g:python3_host_prog
  " let g:ale_python_isort_options = '-m isort'
  " let g:ale_python_mypy_executable = g:python3_host_prog
  " let g:ale_python_mypy_options = '-m mypy –ignore-missing-imports'

  " QuickRun
  let g:quickrun_config = get(g:, 'quickrun_config', {})
  if has('win32') || has('win64')
    let g:quickrun_config['python'] = {
    \   "hook/output_encode/enable" : 1,
    \   "hook/output_encode/encoding" : "cp932",
    \}
  endif
'''
